language: ruby
rvm:
  - 2.1.5
  - 2.2.2
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
cache: bundler
gemfile:
  - gemfiles/rspec_3.0.gemfile
  - gemfiles/rspec_3.1.gemfile
  - gemfiles/rspec_3.2.gemfile
  - gemfiles/rspec_3.3.gemfile
  - gemfiles/rspec_3.4.gemfile
